name: confesi
description: mobile client

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

isar_version: &isar_version 3.1.0

environment:
  sdk: ">=3.0.0 <=3.1.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  google_fonts: ^4.0.0
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  custom_refresh_indicator: ^1.2.1
  # visibility_detector: ^0.3.3
  # infinite_scroll_pagination: ^3.2.0
  scrollable_positioned_list: ^0.3.2
  # dio: ^4.0.6
  # mongo_dart: ^0.7.4+1
  equatable: ^2.0.3
  internet_connection_checker: ^0.0.1+4
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  jwt_decode: ^0.3.1
  keyboard_attachable: ^2.1.0
  flutter_slidable: ^2.0.0
  flutter_keyboard_visibility: ^5.3.0
  confetti: ^0.7.0
  local_auth: ^2.1.2
  sticky_headers: ^0.3.0+2
  shake: ^2.1.0
  # flutter_staggered_grid_view: ^0.6.2
  visibility_detector: ^0.3.3
  flutter_shake_animated: ^0.0.5
  # flutter_sticky_header: ^0.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  page_transition: ^2.0.9
  flutter_native_splash: ^2.2.10+1
  back_button_interceptor: ^6.0.2
  scrollable: ^1.0.3
  url_launcher: ^6.1.6
  permission_handler: ^10.2.0
  share_plus: ^6.3.0
  cached_network_image: ^3.2.2
  map_launcher: ^2.5.0+1
  animated_text_kit: ^4.2.2
  link_preview_generator: ^1.2.0
  any_link_preview: ^2.0.9
  pie_chart: ^5.3.2
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^8.2.0
  drift: ^2.6.0
  image_cropper: ^1.4.0
  flutter_reorderable_list: ^1.3.1
  photo_view: ^0.14.0
  sqlite3_flutter_libs: ^0.5.13
  path: ^1.8.2
  path_provider: ^2.0.14
  firebase_analytics: ^10.4.4
  screenshot: ^2.1.0
  screenshot_callback: ^2.0.3
  hive_generator: ^2.0.0
  firebase_auth: ^4.7.1
  firebase_remote_config: ^4.2.4
  firebase_performance: ^0.9.2+4
  firebase_crashlytics: ^3.3.4
  go_router: ^10.0.0
  provider: ^6.0.5
  riverpod: ^2.3.6
  cupertino_will_pop_scope: ^1.2.1
  uuid: ^3.0.7
  geolocator: ^9.0.2
  ordered_set: ^5.0.1
  app_links: ^3.4.3
  image_picker: ^1.0.2
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  # shimmer: ^2.0.0
  # open_settings: ^2.0.2
  # animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  drift_dev: ^2.6.0
  build_runner: any
  # hive_generator: ^1.1.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: 111111

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/showcase/
    - assets/images/universities/
    - assets/images/achievements/
    - assets/dummy_json/
    - assets/images/logos/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
